### ISSUE TITLE
Variable Configs

### ISSUE THREAD

**Issue by jappi00** [DeGraciaMathieu/Manager#11]
Hello,

Thank you for this great package! I have a small problem:

So we have a use case that we want to fill in config values to the driver from the DB. The config values need to be set when we decide which driver we are using:

`$images = (new ServerManager())->driver('hetzner')->getImages();`

Best would be to supply those values to the driver function. Of course, I can overwrite the driver function but I do not think this is the intended way.

I would be happy abbout amy help or idea about this.

**Comment by DeGraciaMathieu** [comment]
Hi,

Thank you for using the package!

You can use the driver creation method to execute specific queries, it is designed to manage driver-specific functionalities.

```php
class ServerManager extends Manager
{
    public function createHetznerDriver()
    {
        $config = // 'database queries?'

        return new Hetzner($config);
    }

    public function getDefaultDriver(): string
    {
        return 'hetzner';
    }
}
```

However, I would recommend employing composition to encapsulate this responsibility within a class, possibly a repository ?

```php
class Hetzner implements Driver
{
    public function __construct(
        private SomeRepository $repository,
    ) {}
}
```

**Comment by jappi00** [comment]
I have solved it with providing the conf vals in the __construct function like this:

```php
    public function __construct(Team|false $team = false, bool $singleton = false, Aggregator $aggregator = new Aggregator())
    {
        $this->team = $team;

        parent::__construct($singleton, $aggregator);
    }
```
