### ISSUE TITLE
Singleton call constructor

### ISSUE THREAD

**Issue by ronnievisser** [DeGraciaMathieu/Manager#5]
Hi,

I think it will be usefull when in the docs you name that when using the $singleton = true in the manager the construct of the parent needs to be called

```php
public function __construct()
{
        parent::__construct();
}
```

Otherwise the Aggregates is not instantiated.

regards

**Comment by DeGraciaMathieu** [comment]
Hi !
Indeed, i will specify on the documentation.
Thank you !
